name: icefloe
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.20.2
  drift_flutter: ^0.1.0
  get: ^4.6.6
  nostr: ^1.5.0
  system_theme: ^3.1.1
  web_socket_channel: ^3.0.1
  bitsdojo_window: ^0.1.6
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.3
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - logo.png
